### ISSUE TITLE
Thumbnail is not creating on linux server

### ISSUE THREAD

**Issue by RV8395** [pawlox/video-thumbnail#2]
Hello sir,
I'm trying this tutorial from last three days.
In windows server it is worked for me. I put some different code for windows server in /config/video-thumbnail.php file is : 

'binaries' => [
        'ffmpeg'  => public_path('/ffmpeg/bin/ffmpeg.exe'),
        'ffprobe' => public_path('/ffmpeg/bin/ffprobe.exe')
    ]
ans it is worked for me.
But in Linux server not worked for me with same code and even with the this code : 

'binaries' => [
        'ffmpeg'  => env('FFMPEG', '/usr/bin/ffmpeg'),
        'ffprobe' => env('FFPROBE', '/usr/bin/ffprobe')
    ]

Please help me with this issue.
Thanks.
Regards.

**Comment by pawlox** [comment]
Hi,

Have you got ffmpeg installed on this Linux server and binaries are present in /usr/bin directory?

Is there any errors in log files?

**Comment by RV8395** [comment]
Actually it is AWS Linux server and i have installed ffmpeg using cmd and binaries are present /usr/bin directory

**Comment by RV8395** [comment]
Here is my ffmpeg details : 

![image](https://user-images.githubusercontent.com/27272204/33903675-2012d350-df9f-11e7-9d24-a54a4793e082.png)

**Comment by pawlox** [comment]
What about logs? Is there any kind of error/failure message there? 

Maybe try generate thubnail manually and see if this works:
`/usr/bin/ffmpeg -i input.mp4 -ss 00:00:01.000 -vframes 1 out.png`

What version of PHP and Laravel have you got?

**Comment by jack1096** [comment]
From log we are getting  this error:
getimagesize(http://xx.xx.xx.xx/public/videos_thumb/ynvO5D9GzUJsLPj8vPlyiOEND0ag9MeFGr4NFu5k.jpg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

In short thumbnail is not generated

Laravel version - 5.4.*
php 5.6.4
Above command is working. I successfully created thumbnail

**Comment by pawlox** [comment]
Can you show me how you call `VideoThumbnail::createThumbnail(...)` method?

**Comment by jack1096** [comment]
VideoThumbnail::createThumbnail(url('/storage/app/accident_report_videos/ynvO5D9GzUJsLPj8vPlyiOEND0ag9MeFGr4NFu5k.mp4'), public_path('files/thumbs/'), '111.jpg', 2, 600, 600);

**Comment by pawlox** [comment]
Hmm, I think that you might passing a wrong video path (first argument), it should be something like `storage_path('/app/accident_report_videos/ynvO5D9GzUJsLPj8vPlyiOEND0ag9MeFGr4NFu5k.mp4')`

**Comment by jack1096** [comment]
Yes  you are right i just changed to this and it start working

VideoThumbnail::createThumbnail(storage_path('app/accident_report_videos/ynvO5D9GzUJsLPj8vPlyiOEND0ag9MeFGr4NFu5k.mp4'), storage_path('app/accident_report_videos/thumbs/'), '1112.jpg', 2, 600, 600);

Thanks for all support

**Comment by daviramadan19** [comment]
hello, I want to ask
why if install this package, on my project local runing
and if server linux ubuntu 'error "VideoThumbnail" not found' ?

**Comment by pakcybershagufta** [comment]
> hello, I want to ask
> why if install this package, on my project local runing
> and if server linux ubuntu 'error "VideoThumbnail" not found' ?


Please run below command

php artisan config:cache

**Comment by chokputtaraksa** [comment]
## I'm sorry, I know where the problems occurred already, I use the video that have timeframe less than 7 seconds, so when I try to create thumbnail at second 7, it failed.


I have read all above comments, but I still cannot solve the problems.
I have stored the video in  `project/public/` instead of `storage/app/public` 

Here are my config and code:
![Screen Shot 2562-11-24 at 00 52 11](https://user-images.githubusercontent.com/13741366/69483034-2391fb00-0e55-11ea-902c-15c862e4fbbf.png)

![Screen Shot 2562-11-24 at 00 53 50](https://user-images.githubusercontent.com/13741366/69483047-34db0780-0e55-11ea-8a83-6f72e89ba739.png)

Here is FFMPEG, and where it is.
![Screen Shot 2562-11-24 at 00 53 26](https://user-images.githubusercontent.com/13741366/69483048-37d5f800-0e55-11ea-9886-e6dbfd17ed97.png)

Here is the error:
![Screen Shot 2562-11-24 at 00 52 56](https://user-images.githubusercontent.com/13741366/69483057-54723000-0e55-11ea-92c2-3e6b42b95a19.png)

The file directory:
![Screen Shot 2562-11-24 at 00 52 37](https://user-images.githubusercontent.com/13741366/69483060-65bb3c80-0e55-11ea-8cf9-c3e82e465995.png)

The source folder permission:
![Screen Shot 2562-11-24 at 00 54 52](https://user-images.githubusercontent.com/13741366/69483086-9e5b1600-0e55-11ea-9a67-03ed2e2570cf.png)

The destination folder permission:
![Screen Shot 2562-11-24 at 00 54 43](https://user-images.githubusercontent.com/13741366/69483089-aca93200-0e55-11ea-9a95-94b69bfa53b7.png)


Please help me I have been doing this more than 8 hrs. I can't find the solution yet.

**Comment by pawel-marciniak** [comment]
@whitedevilza Happy to hear that you found the cause of your problem :) I'm going to make some improvements for this package soon, maybe validating video length could one of them.

**Comment by pawlox** [comment]
@whitedevilza Happy to hear that you found the cause of your problem :) I'm going to make some improvements for this package soon, maybe validating video length could one of them.

**Comment by votivegit** [comment]
Is Pawlox\VideoThumbnail library compatible for below versions ?

Laravel Framework 6.12.0
PHP 7.2.24-0ubuntu0.18.04.2

**Comment by pawlox** [comment]
@votivegit Unfortunately this package is not working with Laravel 6.x (at least when I checked it recently). It is because of phpffmpeg's external dependency, as you can see here - https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/680

**Comment by votivegit** [comment]
@pawlox  thanks for the quick response.

Actually i tried to integrate it since morning and ended up with version issue. :(

**Comment by pawlox** [comment]
@votivegit I will check it after work, in theory they removed monolog dependency from binary driver - https://github.com/alchemy-fr/BinaryDriver/releases

**Comment by votivegit** [comment]
@pawlox okay.

**Comment by deepakAppqik** [comment]
@pawlox 
hello my issue is when i am trying VideoThumbnail::createThumbnail(storage_path('app/video/qDd2ObCfIljsBoJMECE51voQcFBSIQs6ZWQdWCLc.mp4'), storage_path('app/files/thumbs/'), 'thumbs_1.jpg', 2, 1920, 1080); in my controller createthumnail not found in Pawlox\VideoThumbnail\Facade\VideoThumbnail i am getting this
